name: Java CI with Maven and JavaFX

on:
  push:
    branches: 
      - "main"  # Trigger on pushes to the main branch
  pull_request:
    branches: 
      - "main"  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment the workflow will run on

    steps:
    # Step 1: Checkout the repository code
    - uses: actions/checkout@v4

    # Step 2: Set up JDK 21 (Temurin) to compile the Java project
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven  # Cache dependencies to speed up builds

    # Step 3: Install JavaFX runtime for Ubuntu
    - name: Install JavaFX runtime dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjfx

    # Step 4: Build the project using Maven (including JavaFX)
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    # Step 5: Update dependency graph for security and alerts
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
